import { Agent } from "../agents/agent.js";
import { SessionState } from "../orchestrator/state.js";
import { Plan } from "../voting/schemas.js";
import { messageStore, createMessage } from "../ui/message-store.js";

export async function runPhase2Plan(
  state: SessionState,
  agents: Agent[]
): Promise<void> {
  state.phase = "plan_generation";

  if (!state.taskBrief) {
    throw new Error("Cannot generate plans: no task brief available");
  }

  messageStore.push(createMessage("orchestrator", `Generating plans with ${agents.length} agents in parallel...`));

  const planResults = await Promise.allSettled(
    agents.map((agent) =>
      agent
        .generatePlan(state.taskBrief!)
        .then((plan) => ({ agent: agent.name, plan }))
    )
  );

  const plans: Plan[] = [];
  for (const result of planResults) {
    if (result.status === "fulfilled") {
      plans.push(result.value.plan);
      state.plans.set(result.value.plan.plan_id, result.value.plan);

      const stepsStr = result.value.plan.steps.map((s) => `  ${s.step}. ${s.action}`).join("\n");
      const color = agents.find((a) => a.name === result.value.agent)?.color || "white";

      messageStore.push(createMessage("agent", result.value.plan.summary, {
        agentName: result.value.agent,
        color,
        specialty: agents.find((a) => a.name === result.value.agent)?.specialty,
      }));

      messageStore.push(createMessage("dim", `Steps:\n${stepsStr}`));
      messageStore.push(createMessage("dim", `Complexity: ${result.value.plan.estimated_complexity} | Confidence: ${Math.round(result.value.plan.self_confidence * 100)}%`));

      if (result.value.plan.risks.length > 0) {
        messageStore.push(createMessage("warning", `Risks: ${result.value.plan.risks.join(", ")}`));
      }
    } else {
      messageStore.push(createMessage("error", `An agent failed to generate a plan.`));
    }
  }

  if (plans.length === 0) {
    throw new Error("No plans were generated by any agent");
  }

  messageStore.push(createMessage("orchestrator", `${plans.length} plans generated. Ready for voting.`));
}