import { Agent } from "../agents/agent.js";
import { SessionState } from "../orchestrator/state.js";
import { Config, Plan } from "../voting/schemas.js";
import { messageStore, createMessage } from "../ui/message-store.js";

export async function runPhase2Plan(
  state: SessionState,
  agents: Agent[],
  config: Config
): Promise<void> {
  state.phase = "plan_generation";

  if (!state.taskBrief) {
    throw new Error("Cannot generate plans: no task brief available");
  }

  messageStore.push(createMessage("orchestrator", `Generating plans with ${agents.length} agents in parallel...`));

  const planResults = await Promise.allSettled(
    agents.map((agent) =>
      agent
        .generatePlan(state.taskBrief!)
        .then((plan) => ({ agent: agent.name, plan }))
    )
  );

  const plans: Plan[] = [];
  for (const result of planResults) {
    if (result.status === "fulfilled") {
      plans.push(result.value.plan);
      state.plans.set(result.value.plan.plan_id, result.value.plan);

      const stepsStr = result.value.plan.steps.map((s) => `  ${s.step}. ${s.action}`).join("\n");
      const color = agents.find((a) => a.name === result.value.agent)?.color || "white";

      messageStore.push(createMessage("agent", result.value.plan.summary, {
        agentName: result.value.agent,
        color,
        specialty: agents.find((a) => a.name === result.value.agent)?.specialty,
      }));

      messageStore.push(createMessage("dim", `Steps:\n${stepsStr}`));
      messageStore.push(createMessage("dim", `Complexity: ${result.value.plan.estimated_complexity} | Confidence: ${Math.round(result.value.plan.self_confidence * 100)}%`));

      if (result.value.plan.risks.length > 0) {
        messageStore.push(createMessage("warning", `Risks: ${result.value.plan.risks.join(", ")}`));
      }
    } else {
      messageStore.push(createMessage("error", `An agent failed to generate a plan.`));
    }
  }

  if (plans.length === 0) {
    throw new Error("No plans were generated by any agent");
  }

  if (config.features.cross_examination_round) {
    messageStore.push(createMessage("orchestrator", "Cross-examination round: agents are questioning each other's plans..."));
    for (const agent of agents) {
      const targetCandidates = agents.filter((a) => a.name !== agent.name);
      if (targetCandidates.length === 0) continue;
      const target = targetCandidates[Math.floor(Math.random() * targetCandidates.length)];
      const question = await agent.askClarifyingQuestion(plans, target.name);
      if (!question) continue;
      const targetPlan = plans.find((p) => p.agent === target.name);
      if (!targetPlan) continue;
      const response = await target.respondToClarifyingQuestion(question, targetPlan);
      state.crossExaminationMessages.push({ from: agent.name, to: target.name, message: question });
      state.crossExaminationMessages.push({ from: target.name, to: agent.name, message: response });
      messageStore.push(createMessage("agent", `${agent.name} → ${target.name}: ${question}`, {
        agentName: agent.name,
        color: agents.find((a) => a.name === agent.name)?.color || "white",
      }));
      messageStore.push(createMessage("agent", `${target.name} → ${agent.name}: ${response}`, {
        agentName: target.name,
        color: agents.find((a) => a.name === target.name)?.color || "white",
      }));
    }
  }

  messageStore.push(createMessage("orchestrator", `${plans.length} plans generated. Ready for voting.`));
}