import { AgentConfig } from "../voting/schemas.js";

export const DEFAULT_AGENTS: AgentConfig[] = [
  {
    name: "Sonnet",
    provider: "anthropic",
    model: "claude-3-5-sonnet-20241022",
    specialty: "Architecture, Planning",
    color: "cyan",
    enabled: true,
  },
  {
    name: "Opus",
    provider: "anthropic",
    model: "claude-3-opus-20240229",
    specialty: "Deep Reasoning, Review",
    color: "blue",
    enabled: true,
  },
  {
    name: "Haiku",
    provider: "anthropic",
    model: "claude-3-haiku-20240307",
    specialty: "Speed, Summarization",
    color: "green",
    enabled: true,
  },
  {
    name: "GPT4o",
    provider: "openai",
    model: "gpt-4o",
    specialty: "General, Code Gen",
    color: "yellow",
    enabled: true,
  },
  {
    name: "o3",
    provider: "openai",
    model: "o3-mini",
    specialty: "Logical Reasoning",
    color: "orange",
    enabled: true,
  },
  {
    name: "Gemini",
    provider: "google",
    model: "gemini-2.5-pro",
    specialty: "Research, Multimodal",
    color: "magenta",
    enabled: true,
  },
  {
    name: "Mistral",
    provider: "mistral",
    model: "mistral-large-latest",
    specialty: "Concise Answers, Speed",
    color: "white",
    enabled: true,
  },
  {
    name: "DeepSeek",
    provider: "deepseek",
    model: "deepseek-coder",
    specialty: "Low-level Code, DSA",
    color: "red",
    enabled: true,
    base_url: "https://api.deepseek.com/v1",
  },
  {
    name: "Grok",
    provider: "xai",
    model: "grok-3",
    specialty: "Creativity, Brainstorm",
    color: "purple",
    enabled: true,
    base_url: "https://api.x.ai/v1",
  },
  {
    name: "Nemotron",
    provider: "nvidia",
    model: "nvidia/nemotron-4-340b-instruct",
    specialty: "Reasoning, Code Gen",
    color: "magenta",
    enabled: true,
    base_url: "https://integrate.api.nvidia.com/v1",
  },
];